'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle, MapPin, Shield, Star, Award, Phone, Zap, Building2, Fingerprint, Briefcase } from 'lucide-react';
import { services } from '@/data/services';
import { toSlug } from '@/data/locations';
import { pricingTiers, financeInfo } from '@/data/pricing';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Hero } from '@/components/Hero';
import { TrustBadges } from '@/components/TrustBadges';
import { FAQ } from '@/components/FAQ';
import { LeadFormModal } from '@/components/LeadFormModal';
import { siteConfig } from '@/data/site';
import { topAreas, heroContent, problemFraming, clientTypes, serviceCardsHeading, howItWorks, regionalContext, areasSection, pricingSection, trustPoints, homepageFaqs, faqSectionTitle, ctaSection, schemaData } from '@/data/homepage';
const iconMap: Record<string, React.ReactNode> = { Shield:<Shield className="h-6 w-6"/>, Building2:<Building2 className="h-6 w-6"/>, Star:<Star className="h-6 w-6"/>, Zap:<Zap className="h-6 w-6"/>, Fingerprint:<Fingerprint className="h-6 w-6"/>, Award:<Award className="h-6 w-6"/>, MapPin:<MapPin className="h-6 w-6"/>, Phone:<Phone className="h-6 w-6"/>, Briefcase:<Briefcase className="h-6 w-6"/> };
export default function HomePage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context':'https://schema.org','@type':'Organization','@id':siteConfig.url,name:siteConfig.name,description:siteConfig.description,url:siteConfig.url,logo:`${siteConfig.url}/android-chrome-512x512.png`,image:`${siteConfig.url}/android-chrome-512x512.png`,areaServed:{'@type':'AdministrativeArea',name:schemaData.areaServedName,containedInPlace:{'@type':'Country',name:'United States'}},makesOffer:{'@type':'Service',name:schemaData.offerCatalogName,description:'Confidential matching and referral coordination for licensed private investigators in Manhattan.'} }) }} /><LeadFormModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} /><Header onOpenModal={() => setIsModalOpen(true)} /><main className="flex-grow"><Hero title={heroContent.title} subtitle={heroContent.subtitle} image={heroContent.image} onOpenModal={() => setIsModalOpen(true)} /><TrustBadges />
<section className="section-padding bg-white/65"><div className="container-width"><div className="grid items-center gap-14 lg:grid-cols-2"><div><span className="section-kicker">Why clients use us</span><h2 className="text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{problemFraming.heading}</h2><div className="mt-7 space-y-5 text-[1.02rem] leading-8 text-[#5f5752]">{problemFraming.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div><button onClick={() => setIsModalOpen(true)} className="btn-primary mt-8 font-ui text-sm uppercase tracking-[0.08em]">Request a confidential match</button></div><div className="grid grid-cols-2 gap-4"><img src={problemFraming.images[0].src} alt={problemFraming.images[0].alt} className="h-56 w-full col-span-2 rounded-[30px] object-cover shadow-[0_24px_60px_rgba(17,12,10,0.08)]" loading="lazy" /><img src={problemFraming.images[1].src} alt={problemFraming.images[1].alt} className="h-44 w-full rounded-[26px] object-cover shadow-[0_20px_45px_rgba(17,12,10,0.08)]" loading="lazy" /><img src={problemFraming.images[2].src} alt={problemFraming.images[2].alt} className="h-44 w-full rounded-[26px] object-cover shadow-[0_20px_45px_rgba(17,12,10,0.08)]" loading="lazy" /></div></div></div></section>
<section className="section-padding bg-[#1a1514] text-white"><div className="container-width"><div className="mb-12 text-center"><span className="eyebrow border-white/10 bg-white/5 text-brand-300">Case types we serve</span><h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] md:text-5xl">{clientTypes.heading}</h2><p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-white/68">{clientTypes.subheading}</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{clientTypes.cards.map((item,i)=><div key={i} className="rounded-[28px] border border-white/10 bg-white/[0.03] p-7 shadow-[0_18px_50px_rgba(0,0,0,0.16)]"><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-500/15 text-brand-300">{iconMap[item.iconName] || <Award className="h-6 w-6" />}</div><h3 className="font-ui text-xl font-bold text-white">{item.title}</h3><p className="mt-3 text-sm leading-7 text-white/66">{item.desc}</p></div>)}</div></div></section>
<section className="section-padding bg-white"><div className="container-width"><div className="mb-12 flex flex-col items-start justify-between gap-6 lg:flex-row lg:items-end"><div><span className="section-kicker">Investigative specializations</span><h2 className="max-w-3xl text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{serviceCardsHeading.title}</h2></div><p className="max-w-2xl text-lg leading-8 text-[#5f5752]">{serviceCardsHeading.subtitle}</p></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map((service)=><Link key={service.id} href={`/services/${service.slug}/`} className="group premium-card overflow-hidden"><div className="h-52 overflow-hidden bg-[#f4ece8]"><img src={service.image} alt={`${service.title} private investigation support`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /></div><div className="p-6"><h3 className="font-ui text-xl font-bold text-[#171312] transition group-hover:text-brand-600">{service.title}</h3><p className="mt-3 text-sm leading-7 text-[#655d57]">{service.description}</p><span className="mt-5 inline-flex items-center gap-2 font-ui text-sm font-bold uppercase tracking-[0.08em] text-brand-600">{serviceCardsHeading.linkText} <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>)}</div></div></section>
<section id="how-it-works" className="section-padding bg-[#f3ece7]"><div className="container-width"><div className="mb-12 text-center"><span className="eyebrow">How the referral works</span><h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{howItWorks.heading}</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-[#5f5752]">{howItWorks.subheading}</p></div><div className="grid gap-6 md:grid-cols-3">{howItWorks.steps.map((item)=><div key={item.step} className="premium-card relative p-7"><div className="mb-6 font-ui text-[11px] font-bold uppercase tracking-[0.18em] text-brand-500">Step {item.step}</div><h3 className="text-2xl font-bold text-[#171312]">{item.title}</h3><p className="mt-4 text-[0.98rem] leading-7 text-[#5f5752]">{item.desc}</p></div>)}</div><div className="mt-12 text-center"><button onClick={() => setIsModalOpen(true)} className="btn-primary font-ui text-sm uppercase tracking-[0.08em]">Start your confidential inquiry</button><p className="mt-3 text-sm text-[#7a716b]">No obligation. Referral coordination only.</p></div></div></section>
<section className="section-padding bg-white"><div className="container-width"><div className="grid gap-14 lg:grid-cols-2"><div><span className="section-kicker">Manhattan expertise</span><h2 className="text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{regionalContext.heading}</h2><div className="mt-7 space-y-5 text-[1.02rem] leading-8 text-[#5f5752]">{regionalContext.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div></div><div className="space-y-4">{regionalContext.regions.map((item,i)=><div key={i} className="premium-card flex gap-4 p-5"><MapPin className="mt-1 h-5 w-5 flex-shrink-0 text-brand-500" /><div><p className="font-ui text-sm font-bold uppercase tracking-[0.08em] text-[#171312]">{item.label}</p><p className="mt-1 text-sm font-medium text-brand-600">{item.towns}</p><p className="mt-2 text-sm leading-7 text-[#5f5752]">{item.detail}</p></div></div>)}</div></div></div></section>
<section id="why-use-us" className="section-padding bg-[#1a1514] text-white"><div className="container-width"><div className="mb-12 text-center"><span className="eyebrow border-white/10 bg-white/5 text-brand-300">Why choose our network</span><h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] md:text-5xl">{trustPoints.heading}</h2><p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-white/68">{trustPoints.subheading}</p></div><div className="grid gap-6 md:grid-cols-2">{trustPoints.points.map((point,i)=><div key={i} className="rounded-[28px] border border-white/10 bg-white/[0.03] p-7"><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-500/15 text-brand-300">{iconMap[point.iconName] || <CheckCircle className="h-6 w-6" />}</div><h3 className="font-ui text-xl font-bold text-white">{point.title}</h3><p className="mt-3 text-sm leading-7 text-white/68">{point.desc}</p></div>)}</div></div></section>
<section className="section-padding bg-[#f5efeb]"><div className="container-width"><div className="mb-12 flex flex-col items-start justify-between gap-6 lg:flex-row lg:items-end"><div><span className="section-kicker">Coverage</span><h2 className="text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{areasSection.heading}</h2></div><p className="max-w-2xl text-lg leading-8 text-[#5f5752]">{areasSection.subheading}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{topAreas.map((area)=><Link key={area} href={`/location/${toSlug(area)}/`} className="premium-card group flex items-center justify-between p-5"><div><div className="font-ui text-sm font-bold uppercase tracking-[0.08em] text-[#171312]">{area}</div><div className="mt-1 text-sm text-[#6b625c]">Confidential investigator referrals</div></div><ArrowRight className="h-5 w-5 text-brand-500 transition group-hover:translate-x-1" /></Link>)}</div><div className="mt-8"><Link href="/location/" className="btn-secondary font-ui text-sm uppercase tracking-[0.08em]">{areasSection.browseAllText}</Link></div></div></section>
<section className="section-padding bg-white"><div className="container-width"><div className="mb-12 text-center"><span className="eyebrow">Pricing guidance</span><h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{pricingSection.heading}</h2><p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-[#5f5752]">{pricingSection.subheading}</p></div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="grid gap-6 md:grid-cols-3">{pricingTiers.slice(0,3).map((tier)=><div key={tier.slug} className="premium-card p-6"><div className="font-ui text-xs font-bold uppercase tracking-[0.14em] text-brand-500">{tier.treatment}</div><div className="mt-4 text-4xl font-bold tracking-[-0.04em] text-[#171312]">${tier.priceFrom.toLocaleString()}–${tier.priceTo.toLocaleString()}</div><p className="mt-2 text-sm font-medium text-brand-600">{tier.typicalDuration}</p><p className="mt-3 text-sm leading-7 text-[#655d57]">{tier.description}</p><div className="mt-5 flex gap-2 text-sm text-[#4f4742]"><CheckCircle className="mt-0.5 h-4 w-4 flex-shrink-0 text-brand-500" /><span>{tier.serviceIncludes}</span></div></div>)}</div><div className="premium-card p-7"><div className="font-ui text-xs font-bold uppercase tracking-[0.14em] text-brand-500">{pricingSection.financeHeading}</div><h3 className="mt-4 text-3xl font-bold tracking-[-0.04em] text-[#171312]">Retainer-based billing</h3><p className="mt-4 text-[0.98rem] leading-8 text-[#5f5752]">{pricingSection.financeSubheading}</p><p className="mt-4 text-[0.98rem] leading-8 text-[#5f5752]">{financeInfo.description}</p><button onClick={() => setIsModalOpen(true)} className="btn-primary mt-7 font-ui text-sm uppercase tracking-[0.08em]">Request an estimate</button></div></div></div></section>
<section id="faq" className="section-padding bg-[#f3ece7]"><div className="container-width"><div className="mb-10 text-center"><span className="eyebrow">FAQ</span><h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] text-[#171312] md:text-5xl">{faqSectionTitle}</h2></div><FAQ faqs={homepageFaqs} title="" /></div></section>
<section className="section-padding bg-[#171312] text-white"><div className="container-width"><div className="rounded-[36px] border border-white/10 bg-[linear-gradient(135deg,rgba(185,55,41,0.32),rgba(255,255,255,0.05))] px-8 py-10 shadow-[0_28px_70px_rgba(0,0,0,0.22)] md:px-12 md:py-14"><div className="max-w-3xl"><span className="eyebrow border-white/10 bg-white/5 text-brand-300">Final step</span><h2 className="mt-6 text-4xl font-bold tracking-[-0.04em] md:text-5xl">{ctaSection.heading}</h2><p className="mt-5 text-lg leading-8 text-white/72">{ctaSection.subheading}</p><div className="mt-8 flex flex-col gap-4 sm:flex-row"><button onClick={() => setIsModalOpen(true)} className="btn-primary font-ui text-sm uppercase tracking-[0.08em]">Start your inquiry</button><Link href="/services/" className="btn-secondary !border-white/15 !bg-white/6 !text-white hover:!bg-white/10 font-ui text-sm uppercase tracking-[0.08em]">Review services</Link></div></div></div></div></section>
</main><Footer /></>;
}
